from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.core.mail import send_mail
import random
from django.conf import settings
from seller.models import *
# Create your views here.

def fun1(request):
    return HttpResponse("this is ashwini page")


# def about(request): #this first parameter 'request' points to the HTTP request generated by the browser
#     return HttpResponse('<h2> DJANGO URLS </h2>') 


def index(request):
    product_list = Product.objects.all()
    try:
        u1 = User.objects.get(email = request.session['email'])
        return render(request, 'index.html', {'userdata':u1, 'all_products': product_list})
    except:
        return render(request, 'index.html', {'all_products': product_list})

def about(request):
    try:
        u1 = User.objects.get(email = request.session['email'])
        return render(request, 'about.html', {'userdata':u1})
    except:
        return render(request, 'about.html')

def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        #method post hai aur row create karna hai

        #ye condition password aur confirm password ke liye
        if request.POST['password'] == request.POST['cpassword']:
            try:
                u1 = User.objects.get(email = request.POST['email'])
                return render(request, 'register.html', {'msg': 'Email Already Exists'})
            except:
                #agar register page pe enter kiya hua email db nahi hai\
                global c_otp, data_list
                c_otp = random.randint(1000,9999)
                data_list = [
                    request.POST['fname'],
                    request.POST['lname'],
                    request.POST['email'],
                    request.POST['password']
                ]
                s = 'Welcome to Ecommerce'
                m = f'Your OTP is {c_otp}'
                fm = settings.EMAIL_HOST_USER
                rl = [request.POST['email']]
                send_mail(s, m, fm, rl)
                return render(request, 'otp.html')
        
        else:
            return render(request, 'register.html', {'msg': 'Both passwords DO not Match'})
        
        
        

def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        #ye POST naam ki dict mein login form se data aa rha hai
        # print(request.POST['email'])

        try:
        # form mein se jo email aaya hai wo email wali row db mein se get kar rhe hain
            u1 = User.objects.get(email = request.POST['email'])
            # error nahi aaya matalab row mil gya, now passwd check karo 
            if request.POST['passwd'] == u1.password:
                request.session['email'] = request.POST['email'] #ye line pe login ho gaya
                return redirect('index')
            else:
                return render(request, 'login.html', {'msg': 'Invalid password'})

        except:
            return render(request, 'login.html', {'msg': 'Email Does Not Exist'})

def otp(request):
    if int(request.POST['u_otp']) == c_otp:
        User.objects.create(
            first_name = data_list[0],
            last_name = data_list[1],
            email = data_list[2],
            password = data_list[3]
        )
        return render(request, 'register.html', {'msg': 'Successfully Account Created!!'})
    else:
        return render(request, 'otp.html', {'msg': 'Invalid OTP'})
    

def contact(request):
    try:
        u1 = User.objects.get(email = request.session['email'])
        return render(request, 'contact.html', {'userdata': u1})
    except:
        return render(request, 'contact.html')


def faqs(request):
    try:
        u1 = User.objects.get(email = request.session['email'])
        return render(request, 'faqs.html', {'userdata': u1})
    except:
        return render(request, 'faqs.html')
    

def logout(request):
    del request.session['email']
    return redirect('index')


def add_to_cart(request, pk):
    try:
        u1 = User.objects.get(email = request.session['email'])
        p1 = Product.objects.get(id = pk)
        Cart.objects.create(
            #ForeignKey wali field hoti hai to obj dena hai
            buyer = u1, 
            product = p1
        )
        return HttpResponse('added')
    except:
        return redirect('login')