from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def fun1(request):
    return HttpResponse("this is ashwini page")


# def about(request): #this first parameter 'request' points to the HTTP request generated by the browser
#     return HttpResponse('<h2> DJANGO URLS </h2>') 


def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')